name: "dependency-check"
version: "1.0.0"
usage: "Check Helm chart dependencies compatibility"
description: |-
  A Helm plugin that validates chart dependencies by checking
  deployed releases compatibility with semver constraints.
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/bin/helm-depcheck"
platformCommand:
  - os: linux
    arch: amd64
    command: "$HELM_PLUGIN_DIR/helm-depcheck"
  - os: linux
    arch: arm64
    command: "$HELM_PLUGIN_DIR/helm-depcheck"
  - os: darwin
    arch: amd64
    command: "$HELM_PLUGIN_DIR/helm-depcheck"
  - os: darwin
    arch: arm64
    command: "$HELM_PLUGIN_DIR/helm-depcheck"
  - os: windows
    arch: amd64
    command: "$HELM_PLUGIN_DIR/helm-depcheck.exe"